### ISSUE TITLE
file ino for  attiny 85 not found in master download 

### ISSUE THREAD

**Issue by zagarolo** [mcore1976/jammer#1]
file ino for  attiny85 not found in master download

**Comment by zagarolo** [comment]
50 micro  pulse for attiny13, no 100 micro pulse attiny85

**Comment by mcore1976** [comment]
> file ino for attiny85 not found in master download

there is jammer.ino file that suits ATTINY85

**Comment by mcore1976** [comment]
> 

Please chane this value from "50" to any required like "100"

for(sequence=1; sequence<50; sequence++)
