### ISSUE TITLE
[ QUESTION ] about transmitter hardware

### ISSUE THREAD

**Issue by flakka2022** [mcore1976/jammer#3]
it is possible to use LoRa instead of fs1000a (with code modification and use Appropriate microcontroller ) ? is LoRa capable of transmit this kind of data/pulse/wave continuously ?

**Comment by mcore1976** [comment]
In the specs for LORA Semtech SX1276/77/78/79 based boards we can see the following : "FSK, GFSK, MSK, GMSK, LoRa and OOK modulation". However connectivity with these boards require SPI bus therefor it is completely different than driving single DOUT pin of FS1000A.  
Conclusion - these board cannot be used with this kind of source code. LoRA boards are rather CC1101 like boards.
